# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import james_runtime_pb2 as james__runtime__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in james_runtime_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class JamesRuntimeStub:
    """============ Service ============

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Complete = channel.unary_unary(
                '/james.runtime.v1.JamesRuntime/Complete',
                request_serializer=james__runtime__pb2.CompletionRequest.SerializeToString,
                response_deserializer=james__runtime__pb2.CompletionResponse.FromString,
                _registered_method=True)
        self.StreamComplete = channel.unary_stream(
                '/james.runtime.v1.JamesRuntime/StreamComplete',
                request_serializer=james__runtime__pb2.CompletionRequest.SerializeToString,
                response_deserializer=james__runtime__pb2.Chunk.FromString,
                _registered_method=True)
        self.RouteModel = channel.unary_unary(
                '/james.runtime.v1.JamesRuntime/RouteModel',
                request_serializer=james__runtime__pb2.RoutingRequest.SerializeToString,
                response_deserializer=james__runtime__pb2.RoutingDecision.FromString,
                _registered_method=True)
        self.SelectRuntime = channel.unary_unary(
                '/james.runtime.v1.JamesRuntime/SelectRuntime',
                request_serializer=james__runtime__pb2.RuntimeRequest.SerializeToString,
                response_deserializer=james__runtime__pb2.RuntimeSelection.FromString,
                _registered_method=True)
        self.GetHardwareProfile = channel.unary_unary(
                '/james.runtime.v1.JamesRuntime/GetHardwareProfile',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=james__runtime__pb2.HardwareProfile.FromString,
                _registered_method=True)
        self.GetModelRegistry = channel.unary_unary(
                '/james.runtime.v1.JamesRuntime/GetModelRegistry',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=james__runtime__pb2.ModelRegistry.FromString,
                _registered_method=True)
        self.GetCostReport = channel.unary_unary(
                '/james.runtime.v1.JamesRuntime/GetCostReport',
                request_serializer=james__runtime__pb2.CostReport.SerializeToString,
                response_deserializer=james__runtime__pb2.CostReport.FromString,
                _registered_method=True)
        self.UpdateBudget = channel.unary_unary(
                '/james.runtime.v1.JamesRuntime/UpdateBudget',
                request_serializer=james__runtime__pb2.BudgetPolicy.SerializeToString,
                response_deserializer=james__runtime__pb2.BudgetStatus.FromString,
                _registered_method=True)
        self.StreamEvents = channel.unary_stream(
                '/james.runtime.v1.JamesRuntime/StreamEvents',
                request_serializer=james__runtime__pb2.EventFilter.SerializeToString,
                response_deserializer=james__runtime__pb2.RuntimeEvent.FromString,
                _registered_method=True)


class JamesRuntimeServicer:
    """============ Service ============

    """

    def Complete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamComplete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RouteModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SelectRuntime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHardwareProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelRegistry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCostReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBudget(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JamesRuntimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Complete': grpc.unary_unary_rpc_method_handler(
                    servicer.Complete,
                    request_deserializer=james__runtime__pb2.CompletionRequest.FromString,
                    response_serializer=james__runtime__pb2.CompletionResponse.SerializeToString,
            ),
            'StreamComplete': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamComplete,
                    request_deserializer=james__runtime__pb2.CompletionRequest.FromString,
                    response_serializer=james__runtime__pb2.Chunk.SerializeToString,
            ),
            'RouteModel': grpc.unary_unary_rpc_method_handler(
                    servicer.RouteModel,
                    request_deserializer=james__runtime__pb2.RoutingRequest.FromString,
                    response_serializer=james__runtime__pb2.RoutingDecision.SerializeToString,
            ),
            'SelectRuntime': grpc.unary_unary_rpc_method_handler(
                    servicer.SelectRuntime,
                    request_deserializer=james__runtime__pb2.RuntimeRequest.FromString,
                    response_serializer=james__runtime__pb2.RuntimeSelection.SerializeToString,
            ),
            'GetHardwareProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHardwareProfile,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=james__runtime__pb2.HardwareProfile.SerializeToString,
            ),
            'GetModelRegistry': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelRegistry,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=james__runtime__pb2.ModelRegistry.SerializeToString,
            ),
            'GetCostReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCostReport,
                    request_deserializer=james__runtime__pb2.CostReport.FromString,
                    response_serializer=james__runtime__pb2.CostReport.SerializeToString,
            ),
            'UpdateBudget': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBudget,
                    request_deserializer=james__runtime__pb2.BudgetPolicy.FromString,
                    response_serializer=james__runtime__pb2.BudgetStatus.SerializeToString,
            ),
            'StreamEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=james__runtime__pb2.EventFilter.FromString,
                    response_serializer=james__runtime__pb2.RuntimeEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'james.runtime.v1.JamesRuntime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('james.runtime.v1.JamesRuntime', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class JamesRuntime:
    """============ Service ============

    """

    @staticmethod
    def Complete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/james.runtime.v1.JamesRuntime/Complete',
            james__runtime__pb2.CompletionRequest.SerializeToString,
            james__runtime__pb2.CompletionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamComplete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/james.runtime.v1.JamesRuntime/StreamComplete',
            james__runtime__pb2.CompletionRequest.SerializeToString,
            james__runtime__pb2.Chunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RouteModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/james.runtime.v1.JamesRuntime/RouteModel',
            james__runtime__pb2.RoutingRequest.SerializeToString,
            james__runtime__pb2.RoutingDecision.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SelectRuntime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/james.runtime.v1.JamesRuntime/SelectRuntime',
            james__runtime__pb2.RuntimeRequest.SerializeToString,
            james__runtime__pb2.RuntimeSelection.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHardwareProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/james.runtime.v1.JamesRuntime/GetHardwareProfile',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            james__runtime__pb2.HardwareProfile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelRegistry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/james.runtime.v1.JamesRuntime/GetModelRegistry',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            james__runtime__pb2.ModelRegistry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCostReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/james.runtime.v1.JamesRuntime/GetCostReport',
            james__runtime__pb2.CostReport.SerializeToString,
            james__runtime__pb2.CostReport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateBudget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/james.runtime.v1.JamesRuntime/UpdateBudget',
            james__runtime__pb2.BudgetPolicy.SerializeToString,
            james__runtime__pb2.BudgetStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/james.runtime.v1.JamesRuntime/StreamEvents',
            james__runtime__pb2.EventFilter.SerializeToString,
            james__runtime__pb2.RuntimeEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
