"use strict";
(() => {
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const esc=v=>String(v??"").replace(/[&<>"\']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","\'":"&#39;"}[c]));
  const now=()=>new Date().toISOString(), clock=v=>{const d=new Date(v||Date.now());return Number.isNaN(d.getTime())?"--:--:--":d.toLocaleTimeString([],{hour12:false});};
  const STATES={IDLE:["CORE","BROAD","Runtime ready."],LISTENING:["INPUT","TIGHT","Input channel active."],UNDERSTANDING:["REASONING","TIGHT","Input is being interpreted."],THINKING:["REASONING","TIGHT","Inference is active."],PLANNING:["PLANNING","TIGHT","Execution plan is active."],SEARCHING:["MEMORY","BROAD","Context or sources are being retrieved."],EXECUTING:["ACTION","TIGHT","A capability is executing through the runtime boundary."],VERIFYING:["VERIFY","TIGHT","Output or execution result is being verified."],COMPLETED:["OUTPUT","BROAD","Latest execution completed."],WAITING:["INPUT","TIGHT","Runtime is waiting for input or approval."],LEARNING:["MEMORY","BROAD","State or knowledge is being consolidated."],WARNING:["VERIFY","TIGHT","A warning condition is active."],ERROR:["RECOVERY","TIGHT","An execution error is active."],RECOVERING:["RECOVERY","TIGHT","Runtime recovery is active."],RESOURCE_LIMITED:["CORE","TIGHT","Resource admission is limiting execution."],SECURITY_LOCK:["VERIFY","TIGHT","A security or policy gate is blocking execution."],SLEEPING:["CORE","BROAD","Runtime is in a low-activity state."],OFFLINE:["CORE","BROAD","Runtime API is unreachable."]};
  const store={connected:false,state:"OFFLINE",zone:"CORE",focus:"BROAD",detail:"Connecting to JAMES…",snapshot:{},sections:{},events:[],errors:[],messages:[],signals:[],tab:localStorage.getItem("james.tab")||"overview",lastEvent:0,eventRate:0,ws:null,retry:0};
  try{store.messages=JSON.parse(localStorage.getItem("james.chat")||"[]")}catch{store.messages=[]}
  store.settings=Object.assign({persistChat:true,notifications:true,reducedMotion:matchMedia("(prefers-reduced-motion: reduce)").matches},JSON.parse(localStorage.getItem("james.settings")||"{}"));
  const persist=()=>{localStorage.setItem("james.tab",store.tab);localStorage.setItem("james.settings",JSON.stringify(store.settings));if(store.settings.persistChat)localStorage.setItem("james.chat",JSON.stringify(store.messages.slice(-80)))};
  const setState=(s,source="runtime")=>{if(!STATES[s])s="IDLE";store.state=s;[store.zone,store.focus,store.detail]=STATES[s];document.documentElement.dataset.state=s;
    $("#brain-state").textContent=s;$("#brain-detail").textContent=store.detail;$("#brain-zone").textContent=store.zone;$("#intent-focus").textContent=store.focus;$("#context-focus").textContent=source==="event"?"EVENT-DRIVEN CONTEXT":(store.snapshot.core_status||"SYSTEM CONTEXT");$("#foot-state").textContent=s;$("#mode-label").textContent=store.connected?"VOID / LIVE":"VOID / OFFLINE";$("#intent-mode").textContent=s==="IDLE"?"READY":s;$("#connection-label").textContent=store.connected?"ONLINE":"OFFLINE";$("#conn-dot").classList.toggle("online",store.connected);$("#security-label").textContent=store.snapshot.security|| (store.connected?"AUTHENTICATED PATH":"LOOPBACK / DISCONNECTED");renderIntent();};
  const derive=e=>{const t=String(e?.event_type||e?.type||"").toLowerCase(),p=JSON.stringify(e?.payload||{}).toLowerCase();
    if(/security|policy|permission|auth|approval/.test(t)&&/deny|block|lock|reject|ask/.test(t+" "+p))return"SECURITY_LOCK";
    if(/error|failed|failure/.test(t))return"ERROR";if(/recover/.test(t))return"RECOVERING";if(/verify|verified/.test(t))return"VERIFYING";if(/execute|capability\.(run|executed)|task\.(started|running)/.test(t))return"EXECUTING";if(/plan/.test(t))return"PLANNING";if(/search|research/.test(t))return"SEARCHING";if(/think|infer|ai/.test(t))return"THINKING";if(/memory|learn|consolid/.test(t))return"LEARNING";if(/wait|blocked|paused/.test(t))return"WAITING";if(/complete|done|ready/.test(t))return"COMPLETED";return null;};
  const applyIntent=intent=>{if(!intent?.brain_state)return false;const state=String(intent.brain_state).toUpperCase();if(!STATES[state])return false;store.state=state;store.zone=String(intent.zone||STATES[state][0]).toUpperCase();store.focus=String(intent.focus||STATES[state][1]).toUpperCase();store.detail=intent.detail||intent.reason||STATES[state][2];store.snapshot.ui_intent=intent;document.documentElement.dataset.state=state;$("#brain-state").textContent=state;$("#brain-detail").textContent=store.detail;$("#brain-zone").textContent=store.zone;$("#intent-focus").textContent=store.focus;$("#context-focus").textContent="RUNTIME UI INTENT";$("#foot-state").textContent=state;$("#intent-mode").textContent=state==="IDLE"?"READY":state;return true;};
  const addEvent=e=>{if(!e)return;const n={id:e.id||crypto.randomUUID?.()||String(Date.now()),event_type:e.event_type||e.type||"event",source:e.source||"runtime",severity:e.severity||"info",timestamp:e.timestamp||now(),payload:e.payload||{}};store.events.unshift(n);store.events=store.events.slice(0,120);store.lastEvent=Date.now();store.eventRate=Math.min(999,store.eventRate+1);store.signals.push({event:n,t:0});store.signals=store.signals.slice(-24);if(/error|failed|failure|denied|security/i.test(n.event_type+JSON.stringify(n.payload))){store.errors.unshift(n);store.errors=store.errors.slice(0,30)}if(n.event_type==="ui.intent"||n.type==="ui.intent"){applyIntent(n.payload||n);renderAll();return}const s=derive(n);if(s)setState(s,"event");renderAll();};
  async function api(path,opt={}){const r=await fetch(path,{headers:{"Accept":"application/json","Content-Type":"application/json"},...opt});if(!r.ok)throw Error(r.status+" "+r.statusText);const t=await r.text();return t?JSON.parse(t):null;}
  async function refresh(){try{const h=await api("/api/v1/health");store.connected=true;Object.assign(store.snapshot,h||{});const d=await Promise.allSettled([api("/api/v1/dashboard/status"),api("/api/v1/data/status")]);if(d[0].status==="fulfilled")Object.assign(store.snapshot,d[0].value||{});if(d[1].status==="fulfilled")store.sections.status=d[1].value;
      const intent=await api("/api/v1/ui/intent").catch(()=>null);
      if(intent?.brain_state){ applyIntent(intent); } else if(store.state==="OFFLINE") setState("IDLE");
      renderAll()}catch(e){store.connected=false;setState("OFFLINE","transport");$("#chat-status").textContent="Runtime API unavailable — retrying.";renderAll();}}
  function connect(){if(store.ws?.readyState<=1)return;const p=location.protocol==="https:"?"wss":"ws",w=new WebSocket(p+"://"+location.host+"/ws/v1/events");store.ws=w;w.onopen=()=>{store.retry=0;store.connected=true;if(store.state==="OFFLINE")setState("IDLE");refresh()};w.onmessage=e=>{try{addEvent(JSON.parse(e.data))}catch{}};w.onclose=()=>{store.ws=null;store.retry++;if(!store.connected){setState("OFFLINE","transport");}setTimeout(connect,Math.min(10000,1000*2**(store.retry-1)))};w.onerror=()=>{try{w.close()}catch{}};}
  function metrics(){if(Date.now()-store.lastEvent>5000)store.eventRate=Math.max(0,store.eventRate*.9);const s=store.snapshot,m=s.memory_entries??store.sections.memory?.total??"--",tasks=(s.tasks_pending??0)+(s.tasks_running??0);$("#memory-count").textContent=m;$("#task-count").textContent=Number.isFinite(tasks)?tasks:"--";$("#capability-count").textContent=s.capabilities??"--";$("#event-count").textContent=store.events.length+" EVENTS";$("#event-rate").textContent=store.eventRate.toFixed(1)+"/s";const a={OFFLINE:0,IDLE:.04,SLEEPING:.01,LISTENING:.25,UNDERSTANDING:.45,THINKING:.55,PLANNING:.65,SEARCHING:.55,EXECUTING:.85,VERIFYING:.75,COMPLETED:.3,WAITING:.25,LEARNING:.45,WARNING:.8,ERROR:.95,RECOVERING:.5,RESOURCE_LIMITED:.35,SECURITY_LOCK:.9}[store.state]??.2;$("#activity-value").textContent=Math.round(a*100)+"%";$("#signal-density").textContent=Math.min(100,Math.round(store.events.length/120*100))+"%";$("#uptime").textContent="UPTIME "+uptime();$("#session-clock").textContent=clock();$("#clock").textContent=clock();}
  function uptime(){let s=Math.floor(performance.now()/1000),d=Math.floor(s/86400);s%=86400;let h=Math.floor(s/3600);s%=3600;let m=Math.floor(s/60);return d?d+"d "+String(h).padStart(2,"0")+"h":String(h).padStart(2,"0")+":"+String(m).padStart(2,"0")+":"+String(s%60).padStart(2,"0");}
  function renderContext(){const h=$("#context-layer");const items=[...(store.events.slice(0,6).map(e=>({a:e.event_type,b:e.source,c:clock(e.timestamp),e})))];if(!items.length)items.push({a:"RUNTIME",b:store.snapshot.core_status||"waiting for runtime",c:store.connected?"connected":"offline"});h.innerHTML=items.map(x=>'<button class="context-item" data-event=\''+esc(JSON.stringify(x.e||{}))+'\'><span class="micro">'+esc(x.a)+'</span><strong>'+esc(x.b)+'</strong><small>'+esc(x.c)+'</small></button>').join("");$$(".context-item",h).forEach(b=>b.onclick=()=>b.dataset.event&&openDrawer(JSON.parse(b.dataset.event)));}
  function renderIntent(){const h=$("#intent-actions");const a=store.state==="OFFLINE"?[["retry","RECONNECT"]]:store.state==="SECURITY_LOCK"?[["system","OPEN SECURITY"],["events","VIEW EVENTS"]]:store.state==="ERROR"?[["events","INSPECT ERROR"],["retry","REFRESH"]]:[["chat","OPEN CHAT"],["system","SYSTEM"],["events","EVENTS"]];h.innerHTML=a.map(x=>'<button data-intent="'+x[0]+'">'+x[1]+"</button>").join("");$$("[data-intent]",h).forEach(b=>b.onclick=()=>intent(b.dataset.intent));}
  function intent(i){if(i==="chat")focusChat();if(i==="system")dashboard(true);if(i==="events")openEvents();if(i==="retry"){refresh();connect()}}
  function renderErrors(){const r=$("#error-rail"),h=$("#error-feed");r.hidden=!store.errors.length;h.innerHTML=store.errors.slice(0,8).map(e=>'<button class="error-item" data-event=\''+esc(JSON.stringify(e))+'\'><b>'+esc(e.event_type)+'</b><span>'+esc(e.source)+" · "+clock(e.timestamp)+"</span></button>").join("");$$(".error-item",h).forEach(b=>b.onclick=()=>openDrawer(JSON.parse(b.dataset.event)));}
  function renderEvents(){const h=$("#event-list");h.innerHTML=store.events.length?store.events.slice(0,80).map(e=>'<button class="event-row" data-event=\''+esc(JSON.stringify(e))+'\'><span class="event-time">'+clock(e.timestamp)+"</span><b>"+esc(e.event_type)+"</b><small>"+esc(e.source)+"</small></button>").join(""):'<div class="empty-state">Waiting for runtime events.</div>';}
  function openDrawer(d){$("#drawer-kicker").textContent=d?.event_type||"JAMES / CONTEXT";$("#drawer-content").innerHTML='<pre class="data-block">'+esc(JSON.stringify(d,null,2))+"</pre>";$("#drawer").classList.add("open");$("#drawer").setAttribute("aria-hidden","false");}
  function closeDrawer(){$("#drawer").classList.remove("open");$("#drawer").setAttribute("aria-hidden","true")}
  function openEvents(){$("#event-panel").classList.add("open");$("#event-panel").setAttribute("aria-hidden","false");renderEvents()}
  function closeEvents(){$("#event-panel").classList.remove("open");$("#event-panel").setAttribute("aria-hidden","true")}
  const labels={overview:"Overview",chat:"Chat",tasks:"Tasks",memory:"Memory",modules:"Modules",ai:"AI",agents:"Agents",devices:"Devices",capabilities:"Capabilities",events:"Events",automation:"Automation",system:"System",security:"Security",settings:"Settings"};
  function dashboard(force){const open=force??$("#dashboard-view").hidden;$("#void-view").hidden=open;$("#dashboard-view").hidden=!open;if(open)loadSection(store.tab)}
  async function loadSection(tab){store.tab=tab;persist();$("#dash-title").textContent=labels[tab]||tab;$$(".tab").forEach(b=>b.classList.toggle("active",b.dataset.tab===tab));const h=$("#dash-content");h.innerHTML='<div class="loading-state">Reading runtime state…</div>';if(tab==="overview"){h.innerHTML=overview();return}if(tab==="chat"){h.innerHTML='<div class="system-chat"><div class="micro">EXECUTION SPINE</div><p>Use the primary Void command surface for live chat.</p><button data-back-chat>FOCUS CHAT</button></div>';return}try{const d=await api("/api/v1/data/"+encodeURIComponent(tab));store.sections[tab]=d;h.innerHTML=dataView(tab,d)}catch(e){h.innerHTML='<div class="empty-state">Section '+esc(tab)+" unavailable: "+esc(e.message)+"</div>";}}
  function overview(){const s=store.snapshot,rows=[["Core",s.core_status],["Modules",s.modules],["Capabilities",s.capabilities],["Agents",s.agents],["Pending",s.tasks_pending],["Running",s.tasks_running],["Memory",s.memory_entries],["Dropped",s.events_dropped]];return '<div class="data-grid">'+rows.map(r=>'<article class="data-card"><span class="micro">'+r[0]+'</span><strong>'+esc(r[1]??"--")+"</strong></article>").join("")+'</div><pre class="data-block">'+esc(JSON.stringify(s,null,2))+"</pre>";}
  function dataView(tab,d){if(d==null)return'<div class="empty-state">No data.</div>';if(Array.isArray(d))return'<div class="data-list">'+d.slice(0,100).map((x,i)=>'<article class="data-row"><b>'+(i+1)+'</b><pre>'+esc(JSON.stringify(x,null,2))+"</pre></article>").join("")+"</div>";return'<div class="data-heading"><span class="micro">'+esc(labels[tab]||tab)+'</span><span>LIVE RUNTIME DATA</span></div><div class="data-list">'+Object.entries(d).map(([k,v])=>'<article class="data-row"><span class="micro">'+esc(k)+'</span><pre>'+esc(typeof v==="string"?v:JSON.stringify(v,null,2))+"</pre></article>").join("")+"</div>";}
  function renderChat(){const h=$("#chat-history");h.innerHTML=store.messages.slice(-40).map(m=>'<article class="message '+(m.role==="user"?"user":"assistant")+'"><div class="message-meta">'+esc(m.role)+" · "+clock(m.timestamp)+'</div><div class="message-body">'+esc(m.content)+"</div></article>").join("");h.scrollTop=h.scrollHeight;}
  async function send(){const i=$("#chat-input"),content=i.value.trim();if(!content)return;i.value="";store.messages.push({role:"user",content,timestamp:now()});renderChat();persist();setState("UNDERSTANDING","chat");$("#chat-status").textContent="JAMES is processing the request…";try{await refresh();const r=await api("/api/v1/chat",{method:"POST",body:JSON.stringify({message:content})});if(r?.role==="assistant"){store.messages.push({role:"assistant",content:r.content,timestamp:r.timestamp||now()});setState("COMPLETED","chat")}else{setState("WAITING","chat");$("#chat-status").textContent="Input accepted; awaiting runtime events."}persist();renderChat()}catch(e){store.errors.unshift({event_type:"chat.error",source:"void",timestamp:now(),payload:{message:e.message}});setState("ERROR","chat");$("#chat-status").textContent="Request failed. Inspect exceptions.";renderErrors();}}
  function focusChat(){$("#chat-input").focus();$("#chat-input").scrollIntoView({behavior:store.settings.reducedMotion?"auto":"smooth",block:"center"});}
  function openPalette(){$("#palette").classList.add("open");$("#palette").setAttribute("aria-hidden","false");$("#palette-input").focus();palette("")}
  function closePalette(){$("#palette").classList.remove("open");$("#palette").setAttribute("aria-hidden","true")}
  function palette(q){const cmds=[["Ask JAMES","chat"],["System","system"],["Events","events"],["Reconnect","retry"],...Object.keys(labels).map(k=>[labels[k],"tab:"+k])],n=q.toLowerCase();$("#palette-results").innerHTML=cmds.filter(x=>!n||x.join(" ").toLowerCase().includes(n)).slice(0,14).map((x,i)=>'<button class="palette-item" data-command="'+esc(x[1])+'"><b>'+esc(x[0])+'</b><small>Open or execute</small><kbd>'+(i+1)+"</kbd></button>").join("");$$(".palette-item").forEach(b=>b.onclick=()=>run(b.dataset.command));}
  function run(c){closePalette();if(c==="chat")focusChat();else if(c==="system")dashboard(true);else if(c==="events")openEvents();else if(c==="retry"){refresh();connect()}else if(c.startsWith("tab:")){dashboard(true);loadSection(c.slice(4))}}
  function renderAll(){metrics();renderContext();renderErrors();renderEvents();renderChat();renderIntent();}
  document.addEventListener("click",e=>{const target=e.target.closest("[data-action],[data-tab]");const a=target?.dataset.action;const tab=target?.dataset.tab;if(tab){e.preventDefault();dashboard(true);loadSection(tab);return}if(a==="toggle-events")$("#event-panel").classList.contains("open")?closeEvents():openEvents();if(a==="toggle-dashboard")dashboard();if(a==="toggle-settings"){dashboard(true);loadSection("settings")}if(a==="close-events")closeEvents();if(a==="close-drawer")closeDrawer();if(a==="open-palette")openPalette();if(e.target.closest("[data-back-chat]")){$("#dashboard-view").hidden=true;$("#void-view").hidden=false;focusChat()}});
  $("#chat-form").addEventListener("submit",e=>{e.preventDefault();send()});$("#chat-input").addEventListener("focus",()=>{if(store.state==="IDLE")setState("LISTENING","chat")});$("#palette-input").addEventListener("input",e=>palette(e.target.value));
  document.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();openPalette()}if(e.key==="Escape"){closePalette();closeDrawer();closeEvents()}});
  const canvas=$("#brain-canvas"),ctx=canvas.getContext("2d");let W=0,H=0,dpr=1,phase=0;
  const nodes=[["input",.18,.22,"INPUT"],["memory",.78,.22,"MEMORY"],["reason",.30,.47,"REASON"],["core",.50,.45,"CORE"],["plan",.70,.47,"PLAN"],["action",.20,.76,"ACTION"],["verify",.80,.76,"VERIFY"],["output",.50,.88,"OUTPUT"],["recover",.50,.18,"RECOVERY"]];
  const edges=[["input","reason"],["reason","core"],["core","memory"],["memory","reason"],["reason","plan"],["plan","action"],["action","verify"],["verify","output"],["verify","core"],["core","output"],["core","recover"]];
  const pos=id=>{const n=nodes.find(x=>x[0]===id)||nodes[3];return[n[1]*W,n[2]*H]};
  function layout(){const r=canvas.getBoundingClientRect();dpr=Math.min(devicePixelRatio||1,2);W=Math.max(1,r.width);H=Math.max(1,r.height);canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr);ctx.setTransform(dpr,0,0,dpr,0,0)}
  function draw(){ctx.clearRect(0,0,W,H);const active=store.state!=="OFFLINE",pulse=store.settings.reducedMotion?0:(Math.sin(phase)+1)/2,focus=store.zone;
    for(const [a,b] of edges){const p=pos(a),q=pos(b);ctx.beginPath();ctx.moveTo(...p);ctx.lineTo(...q);ctx.strokeStyle=active?"rgba(200,169,107,.18)":"rgba(100,120,140,.07)";ctx.lineWidth=1;ctx.stroke()}
    for(const n of nodes){const p=pos(n[0]),on=n[3]===focus||n[3]==="CORE",r=n[0]==="core"?7:4+(on?pulse*2:0);ctx.beginPath();ctx.arc(...p,r,0,Math.PI*2);ctx.fillStyle=on&&active?"rgba(200,169,107,.9)":"rgba(100,120,140,.24)";ctx.fill();if(on&&active){ctx.beginPath();ctx.arc(...p,r+7+pulse*3,0,Math.PI*2);ctx.strokeStyle="rgba(224,200,138,.25)";ctx.stroke()}}
    const routes={INPUT:["input","reason"],REASONING:["reason","core"],PLANNING:["core","plan"],ACTION:["plan","action"],VERIFY:["action","verify"],OUTPUT:["core","output"],MEMORY:["core","memory"],RECOVERY:["core","recover"],CORE:["core","output"]};
    const route=routes[focus]||routes.CORE;
    if(active&&!store.settings.reducedMotion){
      for(const s of store.signals){if(s.t<1){const p=s.event?.payload||{},z=String(p.zone||p.region||"").toUpperCase();if(!z||z===focus){const a=pos(route[0]),b=pos(route[1]);s.t+=.028;const x=a[0]+(b[0]-a[0])*s.t,y=a[1]+(b[1]-a[1])*s.t;ctx.beginPath();ctx.arc(x,y,2.5,0,Math.PI*2);ctx.fillStyle="rgba(243,247,250,.95)";ctx.fill();}}}
    }
    store.signals=store.signals.filter(s=>s.t<1);phase+=store.settings.reducedMotion?0:.035;requestAnimationFrame(draw)}
  window.addEventListener("resize",layout);layout();draw();renderAll();refresh();connect();setInterval(refresh,5000);setInterval(metrics,500);
})();