//! JAMES-SelfMade: controlled autonomous software evolution.
//!
//! The module deliberately separates proposal, sandbox application, verification,
//! rollback and promotion. A model may propose changes; the runtime decides
//! whether those changes are admissible. The security root and kill controls
//! are outside this module.

use anyhow::{bail, Context, Result};
use chrono::{DateTime, Utc};
use james_capabilities::{CapabilityDefinition, CapabilityRegistry, CapabilityCategory, ExecutionTarget, RiskLevel};
use james_events::{Event, EventBus};
use james_module_host::{ModuleManifest, ModuleType};
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};
use std::process::Stdio;
use std::sync::Arc;
use tokio::process::Command;
use tokio::sync::RwLock;
use uuid::Uuid;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DevelopmentMission {
    pub id: String,
    pub objective: String,
    pub created_at: DateTime<Utc>,
    pub status: MissionStatus,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum MissionStatus {
    Observing,
    Planning,
    Applying,
    Verifying,
    ReadyForPromotion,
    Rejected,
    RolledBack,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChangeProposal {
    pub id: String,
    pub mission_id: String,
    pub objective: String,
    /// Unified git diff generated by an authorized development agent/model.
    pub patch: String,
    pub created_at: DateTime<Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VerificationReport {
    pub passed: bool,
    pub checks: Vec<VerificationCheck>,
    pub stdout: String,
    pub stderr: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VerificationCheck {
    pub name: String,
    pub passed: bool,
}

pub struct SelfMadeModule {
    event_bus: Arc<EventBus>,
    capability_registry: Arc<CapabilityRegistry>,
    running: Arc<RwLock<bool>>,
    root: PathBuf,
    workspace: PathBuf,
}

impl SelfMadeModule {
    pub fn new(
        root: impl Into<PathBuf>,
        event_bus: Arc<EventBus>,
        capability_registry: Arc<CapabilityRegistry>,
    ) -> Self {
        let root = root.into();
        let workspace = root.join(".james").join("selfmade").join("workspace");
        Self {
            event_bus,
            capability_registry,
            running: Arc::new(RwLock::new(false)),
            root,
            workspace,
        }
    }

    pub async fn start(&self) -> Result<()> {
        tokio::fs::create_dir_all(self.workspace.parent().unwrap()).await?;
        *self.running.write().await = true;
        self.emit("selfmade.started", serde_json::json!({
            "workspace": self.workspace,
            "root": self.root,
            "mode": "bounded-autonomous-development"
        })).await;
        Ok(())
    }

    pub async fn stop(&self) -> Result<()> {
        *self.running.write().await = false;
        self.emit("selfmade.stopped", serde_json::json!({})).await;
        Ok(())
    }

    pub async fn is_running(&self) -> bool {
        *self.running.read().await
    }

    pub fn workspace(&self) -> &Path {
        &self.workspace
    }

    /// Build a durable self-inventory from the live runtime registry and the
    /// canonical repository state. This is JAMES's machine-readable answer to
    /// "what am I, what do I have, and what is currently usable?".
    pub async fn observe_self(&self) -> Result<serde_json::Value> {
        let capabilities: Vec<serde_json::Value> = self
            .capability_registry
            .list_all()
            .into_iter()
            .map(|registered| serde_json::json!({
                "id": registered.definition.id,
                "name": registered.definition.name,
                "version": registered.definition.version,
                "provider": registered.definition.provider,
                "category": registered.definition.category,
                "risk_level": registered.definition.risk_level,
                "status": registered.status,
                "experimental": registered.definition.experimental,
                "usage_count": registered.usage_count,
                "last_used": registered.last_used,
            }))
            .collect();

        let git_head = Command::new("git")
            .current_dir(&self.root)
            .args(["rev-parse", "HEAD"])
            .output()
            .await
            .ok()
            .filter(|o| o.status.success())
            .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string());

        let git_status = Command::new("git")
            .current_dir(&self.root)
            .args(["status", "--porcelain=v1"])
            .output()
            .await
            .ok()
            .filter(|o| o.status.success())
            .map(|o| String::from_utf8_lossy(&o.stdout).lines().map(str::to_string).collect::<Vec<_>>())
            .unwrap_or_default();

        let snapshot = serde_json::json!({
            "identity": {
                "name": "JAMES",
                "role": "local-first cognitive runtime and agent operating environment",
                "selfmade_module": "james.selfmade",
                "architecture": "runtime -> event bus -> state -> capabilities -> policy -> execution -> verification -> memory"
            },
            "time": Utc::now(),
            "repository": {
                "root": self.root,
                "workspace": self.workspace,
                "git_head": git_head,
                "git_status": git_status,
            },
            "runtime": {
                "selfmade_running": self.is_running().await,
                "capability_count": capabilities.len(),
                "capabilities": capabilities,
            },
            "autonomy": {
                "observe": true,
                "propose": true,
                "sandbox_apply": true,
                "verify": true,
                "rollback": true,
                "canonical_promotion": false,
                "security_root_mutation": false,
                "kill_control_mutation": false,
            }
        });

        let state_dir = self.workspace.parent().unwrap();
        tokio::fs::create_dir_all(state_dir).await?;
        let state_file = state_dir.join("self-state.json");
        tokio::fs::write(&state_file, serde_json::to_vec_pretty(&snapshot)?).await?;
        self.emit("selfmade.self.observed", serde_json::json!({
            "state_file": state_file,
            "capability_count": capabilities.len(),
            "git_head": snapshot["repository"]["git_head"],
            "dirty": !snapshot["repository"]["git_status"].as_array().map(|v| v.is_empty()).unwrap_or(true)
        })).await;

        Ok(snapshot)
    }


    /// Run one bounded evolution assessment. This deliberately does not
    /// promote source code: it turns observed evidence into a durable mission
    /// that a later development agent can execute in the isolated workspace.
    pub async fn assess_evolution(&self, objective: impl Into<String>) -> Result<DevelopmentMission> {
        let objective = objective.into();
        let self_state = self.observe_self().await?;
        let capability_count = self_state["runtime"]["capability_count"].as_u64().unwrap_or(0);
        let dirty = self_state["repository"]["git_status"]
            .as_array()
            .map(|items| !items.is_empty())
            .unwrap_or(false);

        let mut mission = self.new_mission(&objective);
        mission.status = MissionStatus::Planning;
        let mission_file = self.workspace.parent().unwrap().join("missions");
        tokio::fs::create_dir_all(&mission_file).await?;
        let path = mission_file.join(format!("{}.json", mission.id));

        let assessment = serde_json::json!({
            "mission": mission,
            "evidence": {
                "capability_count": capability_count,
                "repository_dirty": dirty,
                "self_state": self_state,
            },
            "next_phase": "proposal",
            "promotion": "disabled_until_explicit_policy_gate"
        });

        tokio::fs::write(&path, serde_json::to_vec_pretty(&assessment)?).await?;
        self.emit("selfmade.evolution.assessed", serde_json::json!({
            "mission_id": mission.id,
            "objective": objective,
            "mission_file": path,
            "capability_count": capability_count,
            "repository_dirty": dirty
        })).await;
        Ok(mission)
    }

    pub fn new_mission(&self, objective: impl Into<String>) -> DevelopmentMission {
        DevelopmentMission {
            id: Uuid::now_v7().to_string(),
            objective: objective.into(),
            created_at: Utc::now(),
            status: MissionStatus::Observing,
        }
    }

    /// Create an isolated git worktree at a fixed JAMES-owned location.
    /// No source changes are made to the running checkout.
    pub async fn ensure_workspace(&self) -> Result<PathBuf> {
        if self.workspace.join(".git").exists() || self.workspace.join("HEAD").exists() {
            return Ok(self.workspace.clone());
        }
        tokio::fs::create_dir_all(self.workspace.parent().unwrap()).await?;
        let status = Command::new("git")
            .current_dir(&self.root)
            .args(["worktree", "add", "--detach"])
            .arg(&self.workspace)
            .arg("HEAD")
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .output()
            .await
            .context("failed to start git worktree creation")?;
        if !status.status.success() {
            bail!("git worktree creation failed: {}", String::from_utf8_lossy(&status.stderr));
        }
        self.emit("selfmade.workspace.ready", serde_json::json!({
            "workspace": self.workspace
        })).await;
        Ok(self.workspace.clone())
    }

    /// Validate and apply a model-generated patch only inside the isolated worktree.
    pub async fn apply_proposal(&self, proposal: &ChangeProposal) -> Result<VerificationReport> {
        if !self.is_running().await {
            bail!("selfmade module is not running");
        }
        let workspace = self.ensure_workspace().await?;
        self.emit("selfmade.change.proposed", serde_json::json!({
            "mission_id": proposal.mission_id,
            "proposal_id": proposal.id,
            "objective": proposal.objective
        })).await;

        let diff = workspace.join(".james-selfmade.patch");
        tokio::fs::write(&diff, &proposal.patch).await?;

        let check = Command::new("git")
            .current_dir(&workspace)
            .args(["apply", "--check"])
            .arg(&diff)
            .output().await?;
        if !check.status.success() {
            let report = VerificationReport {
                passed: false,
                checks: vec![VerificationCheck { name: "patch-check".into(), passed: false }],
                stdout: String::from_utf8_lossy(&check.stdout).into_owned(),
                stderr: String::from_utf8_lossy(&check.stderr).into_owned(),
            };
            self.emit("selfmade.change.rejected", serde_json::to_value(&report)?).await;
            return Ok(report);
        }

        let applied = Command::new("git")
            .current_dir(&workspace)
            .args(["apply", "--index"])
            .arg(&diff)
            .output().await?;
        if !applied.status.success() {
            bail!("validated patch could not be applied: {}", String::from_utf8_lossy(&applied.stderr));
        }
        self.emit("selfmade.change.applied", serde_json::json!({
            "mission_id": proposal.mission_id,
            "proposal_id": proposal.id
        })).await;

        let report = self.verify_workspace(&workspace).await?;
        if !report.passed {
            let rollback = Command::new("git")
                .current_dir(&workspace)
                .args(["reset", "--hard", "HEAD"])
                .output().await?;
            if !rollback.status.success() {
                bail!("verification failed and rollback failed: {}", String::from_utf8_lossy(&rollback.stderr));
            }
            self.emit("selfmade.change.rolled_back", serde_json::json!({
                "mission_id": proposal.mission_id,
                "proposal_id": proposal.id
            })).await;
        } else {
            self.emit("selfmade.change.verified", serde_json::json!({
                "mission_id": proposal.mission_id,
                "proposal_id": proposal.id
            })).await;
        }
        Ok(report)
    }

    /// Cheap, deterministic verification first. Promotion to the canonical
    /// checkout is intentionally a separate policy-controlled operation.
    async fn verify_workspace(&self, workspace: &Path) -> Result<VerificationReport> {
        let mut checks = Vec::new();
        let mut stdout = String::new();
        let mut stderr = String::new();

        let commands: &[(&str, &[&str])] = &[
            ("git-diff-check", &["diff", "--check"]),
            ("cargo-check", &["check", "--workspace"]),
            ("cargo-test", &["test", "--workspace"]),
        ];

        for (name, args) in commands {
            let output = Command::new(if *name == "git-diff-check" { "git" } else { "cargo" })
                .current_dir(workspace)
                .args(*args)
                .output().await?;
            let ok = output.status.success();
            stdout.push_str(&String::from_utf8_lossy(&output.stdout));
            stderr.push_str(&String::from_utf8_lossy(&output.stderr));
            checks.push(VerificationCheck { name: (*name).into(), passed: ok });
            if !ok {
                return Ok(VerificationReport { passed: false, checks, stdout, stderr });
            }
        }
        Ok(VerificationReport { passed: true, checks, stdout, stderr })
    }

    async fn emit(&self, event_type: &str, payload: serde_json::Value) {
        let _ = self.event_bus.publish(Event::new(event_type, "james-selfmade").with_payload(payload)).await;
    }
}

pub fn manifest() -> ModuleManifest {
    ModuleManifest {
        id: "james.selfmade".into(),
        name: "James-SelfMade".into(),
        version: "0.1.0".into(),
        description: "Bounded autonomous software development and self-improvement runtime".into(),
        module_type: ModuleType::Custom,
        entry_point: "james_selfmade".into(),
        capabilities: vec![
            "selfmade.observe".into(),
            "selfmade.propose".into(),
            "selfmade.verify".into(),
            "selfmade.rollback".into(),
        ],
        dependencies: vec![],
        permissions: vec![],
        configuration_schema: Some(serde_json::json!({
            "type": "object",
            "properties": {
                "workspace": {"type": "string"},
                "autonomous_mode": {"type": "boolean", "default": false}
            }
        })),
        default_config: Some(serde_json::json!({
            "autonomous_mode": false
        })),
        author: Some("JAMES Project".into()),
        homepage: None,
        repository: None,
        license: "MIT".into(),
        tags: vec!["autonomy".into(), "development".into(), "self-improvement".into()],
        min_core_version: "0.1.0".into(),
        platforms: vec!["windows".into(), "linux".into(), "macos".into()],
    }
}

pub async fn register_capabilities(registry: &CapabilityRegistry) -> Result<()> {
    for (id, name, description, risk) in [
        ("selfmade.observe", "SelfMade Observe", "Inspect JAMES runtime and development state", RiskLevel::Low),
        ("selfmade.propose", "SelfMade Propose", "Create a bounded source change proposal", RiskLevel::Medium),
        ("selfmade.verify", "SelfMade Verify", "Run deterministic verification in isolated workspace", RiskLevel::Medium),
        ("selfmade.rollback", "SelfMade Rollback", "Discard an unpromoted self-development workspace change", RiskLevel::High),
    ] {
        registry.register(CapabilityDefinition {
            id: id.into(),
            name: name.into(),
            category: CapabilityCategory::Custom("selfmade".into()),
            version: "1.0.0".into(),
            provider: "james.selfmade".into(),
            description: description.into(),
            risk_level: risk,
            required_permissions: vec![],
            dependencies: vec![],
            input_schema: None,
            output_schema: None,
            execution_target: ExecutionTarget::Local,
            tags: vec!["selfmade".into(), "development".into()],
            deprecated: false,
            experimental: true,
        }, "james.selfmade".into()).await?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use james_events::EventBus;

    #[tokio::test]
    async fn mission_starts_in_observe_state() {
        let bus = Arc::new(EventBus::new(32));
        let registry = Arc::new(CapabilityRegistry::new());
        let module = SelfMadeModule::new(".", bus, registry);
        let mission = module.new_mission("improve runtime");
        assert_eq!(mission.status, MissionStatus::Observing);
        assert!(!mission.id.is_empty());
    }

    #[tokio::test]
    async fn self_observation_contains_identity_and_capabilities() {
        let bus = Arc::new(EventBus::new(32));
        let registry = Arc::new(CapabilityRegistry::new());
        registry.register(CapabilityDefinition {
            id: "test.capability".into(),
            name: "Test".into(),
            category: CapabilityCategory::Custom("test".into()),
            version: "1.0.0".into(),
            provider: "test".into(),
            description: "test".into(),
            risk_level: RiskLevel::Low,
            required_permissions: vec![],
            dependencies: vec![],
            input_schema: None,
            output_schema: None,
            execution_target: ExecutionTarget::Local,
            tags: vec![],
            deprecated: false,
            experimental: false,
        }, "test").await.unwrap();
        let module = SelfMadeModule::new(std::env::temp_dir().join(format!("james-self-{}", Uuid::now_v7())), bus, registry);
        module.start().await.unwrap();
        let state = module.observe_self().await.unwrap();
        assert_eq!(state["identity"]["name"], "JAMES");
        assert_eq!(state["runtime"]["capability_count"], 1);
        let _ = tokio::fs::remove_dir_all(module.root.clone()).await;
    }

    #[tokio::test]
    async fn manifest_is_selfmade() {
        assert_eq!(manifest().id, "james.selfmade");
    }
}
