//! JAMES-SelfMade: controlled autonomous software evolution.
//!
//! The module deliberately separates proposal, sandbox application, verification,
//! rollback and promotion. A model may propose changes; the runtime decides
//! whether those changes are admissible. The security root and kill controls
//! are outside this module.

use anyhow::{bail, Context, Result};
use chrono::{DateTime, Utc};
use james_capabilities::{CapabilityDefinition, CapabilityRegistry, CapabilityCategory, ExecutionTarget, RiskLevel};
use james_events::{Event, EventBus};
use james_module_host::{ModuleManifest, ModuleType};
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};
use std::process::Stdio;
use std::sync::Arc;
use std::future::Future;
use std::pin::Pin;
use tokio::process::Command;
use tokio::sync::RwLock;
use uuid::Uuid;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DevelopmentMission {
    pub id: String,
    pub objective: String,
    pub created_at: DateTime<Utc>,
    pub status: MissionStatus,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum MissionStatus {
    Observing,
    Planning,
    Applying,
    Verifying,
    ReadyForPromotion,
    Rejected,
    RolledBack,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChangeProposal {
    pub id: String,
    pub mission_id: String,
    pub cycle_id: Option<String>,
    pub objective: String,
    /// Unified git diff generated by an authorized development agent/model.
    pub patch: String,
    pub created_at: DateTime<Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VerificationReport {
    pub passed: bool,
    pub checks: Vec<VerificationCheck>,
    pub stdout: String,
    pub stderr: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VerificationCheck {
    pub name: String,
    pub passed: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EvaluationReport {
    pub passed: bool,
    pub baseline_head: Option<String>,
    pub candidate_head: Option<String>,
    pub changed_files: Vec<String>,
    pub verification_passed: bool,
    pub regressions: Vec<String>,
    pub evaluated_at: DateTime<Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EvolutionOutcome {
    pub cycle_id: String,
    pub proposal_id: String,
    pub objective: String,
    pub passed: bool,
    pub verification: VerificationReport,
    pub workspace: PathBuf,
    pub promotion_allowed: bool,
    pub recorded_at: DateTime<Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EvolutionEvidence {
    pub capability_count: usize,
    pub repository_dirty: bool,
    pub git_head: Option<String>,
    pub missing_capabilities: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EvolutionProposal {
    pub id: String,
    pub mission_id: String,
    pub objective: String,
    pub strategy: String,
    pub evidence: EvolutionEvidence,
    pub source_provenance: Vec<String>,
    pub risk_class: String,
    pub promotion_allowed: bool,
    pub created_at: DateTime<Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EvolutionCycle {
    pub id: String,
    pub objective: String,
    pub started_at: DateTime<Utc>,
    pub mission: DevelopmentMission,
    pub evidence: EvolutionEvidence,
    pub proposal: EvolutionProposal,
    pub next_action: String,
}

pub trait DevelopmentAgent: Send + Sync {
    /// Context is borrowed only for the call; implementations must own any data
    /// captured by the returned future so the trait remains object-safe.
    fn propose(&self, context: &str) -> Pin<Box<dyn Future<Output = Result<EvolutionProposal>> + Send + '_>>;

    /// Generate a unified diff for the isolated workspace. The runtime still
    /// validates, applies, tests and rolls back the patch; the agent has no
    /// canonical-repository authority.
    fn generate_patch(&self, _context: &str) -> Pin<Box<dyn Future<Output = Result<String>> + Send + '_>> {
        Box::pin(async { bail!("development agent does not implement patch generation") })
    }
}

fn validate_patch_paths(patch: &str) -> Result<()> {
    const PROTECTED: &[&str] = &[
        "runtime/core/crates/james-capability-broker/",
        "runtime/core/crates/james-core/",
        "runtime/modules/james-system/src/main.rs",
        "ops/scripts/start-james.ps1",
    ];
    let mut seen = 0usize;
    for line in patch.lines() {
        let paths: Vec<&str> = if line.starts_with("diff --git ") {
            line.split_whitespace().skip(2).take(2).collect()
        } else if line.starts_with("--- ") || line.starts_with("+++ ") {
            line.split_whitespace().skip(1).take(1).collect()
        } else {
            Vec::new()
        };
        for raw in paths {
            if raw == "/dev/null" { continue; }
            let normalized = raw.trim_start_matches("a/").trim_start_matches("b/").replace('\\', "/");
            if normalized.starts_with('/')
                || normalized.split('/').any(|component| component == "..")
                || normalized.contains(':')
                || PROTECTED.iter().any(|prefix| normalized == *prefix || normalized.starts_with(prefix))
            {
                bail!("selfmade patch targets unsafe or protected path: {normalized}");
            }
            seen += 1;
        }
    }
    if seen == 0 {
        bail!("selfmade patch contains no file paths");
    }
    Ok(())
}

pub struct SelfMadeModule {
    event_bus: Arc<EventBus>,
    capability_registry: Arc<CapabilityRegistry>,
    running: Arc<RwLock<bool>>,
    root: PathBuf,
    workspace: PathBuf,
}

impl SelfMadeModule {
    pub fn new(
        root: impl Into<PathBuf>,
        event_bus: Arc<EventBus>,
        capability_registry: Arc<CapabilityRegistry>,
    ) -> Self {
        let root = root.into();
        let workspace = root.join(".james").join("selfmade").join("workspace");
        Self {
            event_bus,
            capability_registry,
            running: Arc::new(RwLock::new(false)),
            root,
            workspace,
        }
    }

    pub async fn start(&self) -> Result<()> {
        tokio::fs::create_dir_all(self.workspace.parent().unwrap()).await?;
        *self.running.write().await = true;
        self.emit("selfmade.started", serde_json::json!({
            "workspace": self.workspace,
            "root": self.root,
            "mode": "bounded-autonomous-development"
        })).await;
        Ok(())
    }

    pub async fn stop(&self) -> Result<()> {
        *self.running.write().await = false;
        self.emit("selfmade.stopped", serde_json::json!({})).await;
        Ok(())
    }

    pub async fn is_running(&self) -> bool {
        *self.running.read().await
    }

    pub fn workspace(&self) -> &Path {
        &self.workspace
    }

    /// Build a durable self-inventory from the live runtime registry and the
    /// canonical repository state. This is JAMES's machine-readable answer to
    /// "what am I, what do I have, and what is currently usable?".
    pub async fn observe_self(&self) -> Result<serde_json::Value> {
        let capabilities: Vec<serde_json::Value> = self
            .capability_registry
            .list_all()
            .into_iter()
            .map(|registered| serde_json::json!({
                "id": registered.definition.id,
                "name": registered.definition.name,
                "version": registered.definition.version,
                "provider": registered.definition.provider,
                "category": registered.definition.category,
                "risk_level": registered.definition.risk_level,
                "status": registered.status,
                "experimental": registered.definition.experimental,
                "usage_count": registered.usage_count,
                "last_used": registered.last_used,
            }))
            .collect();

        let git_head = Command::new("git")
            .current_dir(&self.root)
            .args(["rev-parse", "HEAD"])
            .output()
            .await
            .ok()
            .filter(|o| o.status.success())
            .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string());

        let git_status = Command::new("git")
            .current_dir(&self.root)
            .args(["status", "--porcelain=v1"])
            .output()
            .await
            .ok()
            .filter(|o| o.status.success())
            .map(|o| String::from_utf8_lossy(&o.stdout).lines().map(str::to_string).collect::<Vec<_>>())
            .unwrap_or_default();

        let mut top_level = Vec::new();
        let mut entries = tokio::fs::read_dir(&self.root).await?;
        while let Some(entry) = entries.next_entry().await? {
            let name = entry.file_name().to_string_lossy().to_string();
            if name == ".git" || name == ".james" || name == "target" {
                continue;
            }
            let kind = entry.file_type().await?;
            top_level.push(serde_json::json!({
                "name": name,
                "kind": if kind.is_dir() { "directory" } else { "file" }
            }));
        }
        top_level.sort_by(|a, b| {
            a["name"].as_str().unwrap_or("").cmp(b["name"].as_str().unwrap_or(""))
        });

        let workspace_manifests = [
            "runtime/core/Cargo.toml",
            "runtime/modules/Cargo.toml",
            "runtime/python/sidecar/pyproject.toml",
            "runtime/tools/discovery/package.json",
        ];
        let manifests = workspace_manifests.iter()
            .map(|relative| serde_json::json!({
                "path": relative,
                "exists": self.root.join(relative).exists()
            }))
            .collect::<Vec<_>>();

        let repository_model = serde_json::json!({
            "schema_version": 1,
            "top_level": top_level,
            "workspace_manifests": manifests,
            "protected_roots": [
                "runtime/core/crates/james-capability-broker/",
                "runtime/core/crates/james-core/",
                "runtime/modules/james-system/src/main.rs",
                "ops/scripts/start-james.ps1"
            ],
            "generated_at": Utc::now()
        });
        let model_file = self.workspace.parent().unwrap().join("repository-model.json");
        tokio::fs::create_dir_all(self.workspace.parent().unwrap()).await?;
        tokio::fs::write(&model_file, serde_json::to_vec_pretty(&repository_model)?).await?;

        let snapshot = serde_json::json!({
            "identity": {
                "name": "JAMES",
                "role": "local-first cognitive runtime and agent operating environment",
                "selfmade_module": "james.selfmade",
                "architecture": "runtime -> event bus -> state -> capabilities -> policy -> execution -> verification -> memory"
            },
            "time": Utc::now(),
            "repository": {
                "root": self.root,
                "workspace": self.workspace,
                "git_head": git_head,
                "git_status": git_status,
                "model_file": model_file,
                "model": repository_model,
            },
            "runtime": {
                "selfmade_running": self.is_running().await,
                "capability_count": capabilities.len(),
                "capabilities": capabilities,
            },
            "autonomy": {
                "observe": true,
                "propose": true,
                "sandbox_apply": true,
                "verify": true,
                "rollback": true,
                "canonical_promotion": false,
                "security_root_mutation": false,
                "kill_control_mutation": false,
            }
        });

        let state_dir = self.workspace.parent().unwrap();
        tokio::fs::create_dir_all(state_dir).await?;
        let state_file = state_dir.join("self-state.json");
        tokio::fs::write(&state_file, serde_json::to_vec_pretty(&snapshot)?).await?;
        self.emit("selfmade.self.observed", serde_json::json!({
            "state_file": state_file,
            "capability_count": capabilities.len(),
            "git_head": snapshot["repository"]["git_head"],
            "dirty": !snapshot["repository"]["git_status"].as_array().map(|v| v.is_empty()).unwrap_or(true)
        })).await;

        Ok(snapshot)
    }


    /// Run one bounded evolution assessment. This deliberately does not
    /// promote source code: it turns observed evidence into a durable mission
    /// that a later development agent can execute in the isolated workspace.
    pub async fn assess_evolution(&self, objective: impl Into<String>) -> Result<DevelopmentMission> {
        let objective = objective.into();
        let self_state = self.observe_self().await?;
        let capability_count = self_state["runtime"]["capability_count"].as_u64().unwrap_or(0);
        let dirty = self_state["repository"]["git_status"]
            .as_array()
            .map(|items| !items.is_empty())
            .unwrap_or(false);

        let mut mission = self.new_mission(&objective);
        mission.status = MissionStatus::Planning;
        let mission_file = self.workspace.parent().unwrap().join("missions");
        tokio::fs::create_dir_all(&mission_file).await?;
        let path = mission_file.join(format!("{}.json", mission.id));

        let assessment = serde_json::json!({
            "mission": mission,
            "evidence": {
                "capability_count": capability_count,
                "repository_dirty": dirty,
                "self_state": self_state,
            },
            "next_phase": "proposal",
            "promotion": "disabled_until_explicit_policy_gate"
        });

        tokio::fs::write(&path, serde_json::to_vec_pretty(&assessment)?).await?;
        self.emit("selfmade.evolution.assessed", serde_json::json!({
            "mission_id": mission.id,
            "objective": objective,
            "mission_file": path,
            "capability_count": capability_count,
            "repository_dirty": dirty
        })).await;
        Ok(mission)
    }

    /// Execute one complete, bounded evolution planning cycle.
    ///
    /// This is intentionally safe by construction: the cycle may inspect JAMES,
    /// identify gaps and create a machine-readable proposal, but it cannot
    /// promote code to the canonical checkout. Source mutation remains confined
    /// to the isolated worktree and must pass verification before any future
    /// policy-controlled promotion.
    pub async fn run_evolution_cycle(&self, objective: impl Into<String>) -> Result<EvolutionCycle> {
        let objective = objective.into();
        let cycle_id = Uuid::now_v7().to_string();
        let started_at = Utc::now();
        self.emit("selfmade.cycle.started", serde_json::json!({
            "cycle_id": cycle_id,
            "objective": objective
        })).await;

        let self_state = self.observe_self().await?;
        let capabilities = self_state["runtime"]["capabilities"]
            .as_array()
            .cloned()
            .unwrap_or_default();
        let known_ids = capabilities.iter()
            .filter_map(|v| v.get("id").and_then(|v| v.as_str()))
            .map(str::to_string)
            .collect::<std::collections::HashSet<_>>();

        let expected = [
            "selfmade.observe",
            "selfmade.assess",
            "selfmade.propose",
            "selfmade.develop",
            "selfmade.verify",
            "selfmade.rollback",
        ];
        let missing_capabilities = expected.iter()
            .filter(|id| !known_ids.contains(**id))
            .map(|id| (*id).to_string())
            .collect::<Vec<_>>();

        let evidence = EvolutionEvidence {
            capability_count: capabilities.len(),
            repository_dirty: self_state["repository"]["git_status"]
                .as_array().map(|v| !v.is_empty()).unwrap_or(false),
            git_head: self_state["repository"]["git_head"].as_str().map(str::to_string),
            missing_capabilities,
        };
        self.emit("selfmade.gap.detected", serde_json::to_value(&evidence)?).await;

        let mission = self.assess_evolution(&objective).await?;
        let proposal = EvolutionProposal {
            id: Uuid::now_v7().to_string(),
            mission_id: mission.id.clone(),
            objective: objective.clone(),
            strategy: "observe -> gap-detect -> research/reuse -> propose -> sandbox -> verify -> compare -> policy-gate".into(),
            evidence: evidence.clone(),
            source_provenance: vec!["canonical JAMES repository state".into()],
            risk_class: "medium".into(),
            promotion_allowed: false,
            created_at: Utc::now(),
        };

        let proposals_dir = self.workspace.parent().unwrap().join("proposals");
        tokio::fs::create_dir_all(&proposals_dir).await?;
        let proposal_path = proposals_dir.join(format!("{}.json", proposal.id));
        tokio::fs::write(&proposal_path, serde_json::to_vec_pretty(&proposal)?).await?;
        self.emit("selfmade.proposal.created", serde_json::json!({
            "cycle_id": cycle_id,
            "proposal_id": proposal.id,
            "mission_id": mission.id,
            "proposal_file": proposal_path,
            "promotion_allowed": false
        })).await;

        let cycle = EvolutionCycle {
            id: cycle_id,
            objective,
            started_at,
            mission,
            evidence,
            proposal,
            next_action: "development_agent_may_prepare_an_isolated_patch".into(),
        };
        let cycles_dir = self.workspace.parent().unwrap().join("cycles");
        tokio::fs::create_dir_all(&cycles_dir).await?;
        let cycle_path = cycles_dir.join(format!("{}.json", cycle.id));
        tokio::fs::write(&cycle_path, serde_json::to_vec_pretty(&cycle)?).await?;
        self.emit("selfmade.cycle.ready", serde_json::json!({
            "cycle_id": cycle.id,
            "next_action": cycle.next_action,
            "cycle_file": cycle_path
        })).await;
        Ok(cycle)
    }

    /// Ask an authorized development agent to turn an observed cycle into a
    /// concrete proposal. The agent has no execution or promotion authority.
    pub async fn create_agent_proposal(
        &self,
        cycle: &EvolutionCycle,
        agent: &dyn DevelopmentAgent,
    ) -> Result<EvolutionProposal> {
        self.emit("selfmade.development_agent.started", serde_json::json!({
            "cycle_id": cycle.id,
            "objective": cycle.objective
        })).await;
        let context = serde_json::to_string_pretty(cycle)?;
        let proposal = agent.propose(&context).await?;
        if proposal.mission_id != cycle.mission.id || proposal.objective != cycle.objective {
            bail!("development agent proposal is not bound to the active mission");
        }
        if proposal.promotion_allowed {
            bail!("development agent cannot enable canonical promotion");
        }
        let dir = self.workspace.parent().unwrap().join("agent-proposals");
        tokio::fs::create_dir_all(&dir).await?;
        let path = dir.join(format!("{}.json", proposal.id));
        tokio::fs::write(&path, serde_json::to_vec_pretty(&proposal)?).await?;
        self.emit("selfmade.development_agent.proposal_ready", serde_json::json!({
            "cycle_id": cycle.id,
            "proposal_id": proposal.id,
            "path": path,
            "promotion_allowed": false
        })).await;
        Ok(proposal)
    }

    /// Turn a bounded evolution cycle into an actual source change inside the
    /// isolated worktree, then verify it. This is the first real self-development
    /// path: model proposes code, runtime owns application and verification.
    pub async fn develop_cycle(
        &self,
        cycle: &EvolutionCycle,
        agent: &dyn DevelopmentAgent,
    ) -> Result<VerificationReport> {
        let context = serde_json::to_string_pretty(cycle)?;
        self.emit("selfmade.patch.generation.started", serde_json::json!({
            "cycle_id": cycle.id,
            "objective": cycle.objective
        })).await;
        let patch = agent.generate_patch(&context).await?;
        if patch.trim().is_empty() {
            bail!("development agent returned an empty patch");
        }
        let proposal = ChangeProposal {
            id: Uuid::now_v7().to_string(),
            mission_id: cycle.mission.id.clone(),
            cycle_id: Some(cycle.id.clone()),
            objective: cycle.objective.clone(),
            patch,
            created_at: Utc::now(),
        };
        self.emit("selfmade.patch.created", serde_json::json!({
            "cycle_id": cycle.id,
            "proposal_id": proposal.id
        })).await;
        self.apply_proposal(&proposal).await
    }

    pub fn new_mission(&self, objective: impl Into<String>) -> DevelopmentMission {
        DevelopmentMission {
            id: Uuid::now_v7().to_string(),
            objective: objective.into(),
            created_at: Utc::now(),
            status: MissionStatus::Observing,
        }
    }

    /// Create an isolated git worktree at a fixed JAMES-owned location.
    /// No source changes are made to the running checkout.
    pub async fn ensure_workspace(&self) -> Result<PathBuf> {
        if self.workspace.join(".git").exists() || self.workspace.join("HEAD").exists() {
            return Ok(self.workspace.clone());
        }
        tokio::fs::create_dir_all(self.workspace.parent().unwrap()).await?;
        let status = Command::new("git")
            .current_dir(&self.root)
            .args(["worktree", "add", "--detach"])
            .arg(&self.workspace)
            .arg("HEAD")
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .output()
            .await
            .context("failed to start git worktree creation")?;
        if !status.status.success() {
            bail!("git worktree creation failed: {}", String::from_utf8_lossy(&status.stderr));
        }
        self.emit("selfmade.workspace.ready", serde_json::json!({
            "workspace": self.workspace
        })).await;
        Ok(self.workspace.clone())
    }

    /// Validate and apply a model-generated patch only inside the isolated worktree.
    pub async fn apply_proposal(&self, proposal: &ChangeProposal) -> Result<VerificationReport> {
        if !self.is_running().await {
            bail!("selfmade module is not running");
        }
        let workspace = self.ensure_workspace().await?;
        // Every proposal starts from a clean candidate baseline. This prevents
        // failed or stale experiments from contaminating the next evolution cycle.
        for args in [
            vec!["reset", "--hard", "HEAD"],
            vec!["clean", "-fd"],
        ] {
            let cleanup = Command::new("git")
                .current_dir(&workspace)
                .args(&args)
                .output().await?;
            if !cleanup.status.success() {
                bail!("could not reset isolated SelfMade workspace: {}", String::from_utf8_lossy(&cleanup.stderr));
            }
        }
        self.emit("selfmade.change.proposed", serde_json::json!({
            "mission_id": proposal.mission_id,
            "proposal_id": proposal.id,
            "objective": proposal.objective
        })).await;

        let diff = workspace.join(".james-selfmade.patch");
        tokio::fs::write(&diff, &proposal.patch).await?;

        // Defense in depth: validate every git diff path before git sees the patch.\n        validate_patch_paths(&proposal.patch)?;

        let check = Command::new("git")
            .current_dir(&workspace)
            .args(["apply", "--check"])
            .arg(&diff)
            .output().await?;
        if !check.status.success() {
            let report = VerificationReport {
                passed: false,
                checks: vec![VerificationCheck { name: "patch-check".into(), passed: false }],
                stdout: String::from_utf8_lossy(&check.stdout).into_owned(),
                stderr: String::from_utf8_lossy(&check.stderr).into_owned(),
            };
            self.emit("selfmade.change.rejected", serde_json::to_value(&report)?).await;
            return Ok(report);
        }

        let applied = Command::new("git")
            .current_dir(&workspace)
            .args(["apply", "--index"])
            .arg(&diff)
            .output().await?;
        if !applied.status.success() {
            bail!("validated patch could not be applied: {}", String::from_utf8_lossy(&applied.stderr));
        }
        self.emit("selfmade.change.applied", serde_json::json!({
            "mission_id": proposal.mission_id,
            "proposal_id": proposal.id
        })).await;

        let report = self.verify_workspace(&workspace).await?;
        let outcome = EvolutionOutcome {
            cycle_id: proposal.cycle_id.clone().unwrap_or_else(|| proposal.mission_id.clone()),
            proposal_id: proposal.id.clone(),
            objective: proposal.objective.clone(),
            passed: report.passed,
            verification: report.clone(),
            workspace: workspace.clone(),
            promotion_allowed: false,
            recorded_at: Utc::now(),
        };
        let outcomes_dir = self.workspace.parent().unwrap().join("outcomes");
        tokio::fs::create_dir_all(&outcomes_dir).await?;
        let outcome_path = outcomes_dir.join(format!("{}.json", outcome.proposal_id));
        tokio::fs::write(&outcome_path, serde_json::to_vec_pretty(&outcome)?).await?;
        self.emit(if report.passed { "selfmade.verification.passed" } else { "selfmade.verification.failed" },
            serde_json::json!({
                "mission_id": proposal.mission_id,
                "proposal_id": proposal.id,
                "outcome_file": outcome_path,
                "promotion_allowed": false
            })).await;
        if !report.passed {
            let _ = self.record_learning(
                &proposal.objective,
                false,
                "isolated verification failed; candidate was rolled back"
            ).await;
            let rollback = Command::new("git")
                .current_dir(&workspace)
                .args(["reset", "--hard", "HEAD"])
                .output().await?;
            if !rollback.status.success() {
                bail!("verification failed and rollback failed: {}", String::from_utf8_lossy(&rollback.stderr));
            }
            self.emit("selfmade.change.rolled_back", serde_json::json!({
                "mission_id": proposal.mission_id,
                "proposal_id": proposal.id
            })).await;
        } else {
            let _ = self.record_learning(
                &proposal.objective,
                true,
                "isolated candidate passed deterministic verification"
            ).await;
            self.emit("selfmade.change.verified", serde_json::json!({
                "mission_id": proposal.mission_id,
                "proposal_id": proposal.id
            })).await;
        }
        let _ = tokio::fs::remove_file(&diff).await;
        Ok(report)
    }

    /// Persist a learning record after every completed evolution attempt.
    /// This makes success/failure part of the next self-observation instead
    /// of disappearing into transient logs.
    pub async fn record_learning(
        &self,
        objective: &str,
        passed: bool,
        lesson: &str,
    ) -> Result<PathBuf> {
        let dir = self.workspace.parent().unwrap().join("learning");
        tokio::fs::create_dir_all(&dir).await?;
        let record = serde_json::json!({
            "id": Uuid::now_v7(),
            "objective": objective,
            "passed": passed,
            "lesson": lesson,
            "recorded_at": Utc::now(),
            "promotion_allowed": false
        });
        let path = dir.join(format!("{}.json", record["id"].as_str().unwrap_or("learning")));
        tokio::fs::write(&path, serde_json::to_vec_pretty(&record)?).await?;
        self.emit("selfmade.learning.recorded", serde_json::json!({
            "path": path,
            "passed": passed
        })).await;
        Ok(path)
    }

    /// Public capability entrypoint for deterministic verification of the isolated worktree.
    pub async fn verify_workspace_public(&self, workspace: &Path) -> Result<VerificationReport> {
        self.verify_workspace(workspace).await
    }

    /// Evaluate a verified candidate against the canonical baseline before promotion.
    /// Evaluation is deterministic and records the exact candidate delta.
    pub async fn evaluate_workspace(&self) -> Result<EvaluationReport> {
        let workspace = self.ensure_workspace().await?;
        let baseline_head = Command::new("git")
            .current_dir(&self.root)
            .args(["rev-parse", "HEAD"])
            .output().await?
            .ok()
            .filter(|o| o.status.success())
            .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string());

        let candidate_head = Command::new("git")
            .current_dir(&workspace)
            .args(["rev-parse", "HEAD"])
            .output().await?
            .ok()
            .filter(|o| o.status.success())
            .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string());

        let diff = Command::new("git")
            .current_dir(&workspace)
            .args(["diff", "--cached", "--name-only"])
            .output().await?;
        if !diff.status.success() {
            bail!("could not inspect candidate changes");
        }
        let changed_files = String::from_utf8_lossy(&diff.stdout)
            .lines()
            .filter(|line| !line.trim().is_empty())
            .map(str::to_string)
            .collect::<Vec<_>>();

        let verification = self.verify_workspace(&workspace).await?;
        let regressions = if verification.passed { Vec::new() } else {
            verification.checks.iter()
                .filter(|check| !check.passed)
                .map(|check| check.name.clone())
                .collect()
        };
        let report = EvaluationReport {
            passed: verification.passed && !changed_files.is_empty(),
            baseline_head,
            candidate_head,
            changed_files,
            verification_passed: verification.passed,
            regressions,
            evaluated_at: Utc::now(),
        };
        let dir = self.workspace.parent().unwrap().join("evaluations");
        tokio::fs::create_dir_all(&dir).await?;
        let path = dir.join(format!("{}.json", Uuid::now_v7()));
        tokio::fs::write(&path, serde_json::to_vec_pretty(&report)?).await?;
        self.emit("selfmade.evaluation.completed", serde_json::json!({
            "path": path,
            "passed": report.passed,
            "changed_files": report.changed_files,
            "verification_passed": report.verification_passed
        })).await;
        Ok(report)
    }

    /// Promote a verified candidate into the canonical checkout only when the
    /// explicit local policy gate is enabled. This is never model-controlled.
    pub async fn promote_workspace(&self) -> Result<serde_json::Value> {
        if !self.is_running().await {
            bail!("selfmade module is not running");
        }
        if std::env::var("JAMES_SELFMADE_ALLOW_PROMOTION").as_deref() != Ok("1") {
            bail!("canonical promotion is disabled; set JAMES_SELFMADE_ALLOW_PROMOTION=1 for an explicit operator policy gate");
        }

        let root_status = Command::new("git")
            .current_dir(&self.root)
            .args(["status", "--porcelain"])
            .output().await?;
        if !root_status.status.success() {
            bail!("could not inspect canonical repository state");
        }
        if !root_status.stdout.is_empty() {
            bail!("canonical repository must be clean before promotion");
        }

        let workspace = self.ensure_workspace().await?;
        let evaluation = self.evaluate_workspace().await?;
        if !evaluation.passed {
            bail!("candidate must pass behavioral/deterministic evaluation before promotion");
        }

        let diff = Command::new("git")
            .current_dir(&workspace)
            .args(["diff", "--cached", "--binary"])
            .output().await?;
        if !diff.status.success() {
            bail!("could not export verified candidate diff");
        }
        if diff.stdout.is_empty() {
            bail!("candidate contains no changes to promote");
        }

        let patch = String::from_utf8_lossy(&diff.stdout).into_owned();
        validate_patch_paths(&patch)?;
        let patch_file = self.workspace.parent().unwrap().join("promotion.patch");
        tokio::fs::write(&patch_file, patch).await?;

        let applied = Command::new("git")
            .current_dir(&self.root)
            .args(["apply", "--index"])
            .arg(&patch_file)
            .output().await?;
        if !applied.status.success() {
            bail!("promotion failed: {}", String::from_utf8_lossy(&applied.stderr));
        }

        self.emit("selfmade.change.promoted", serde_json::json!({
            "workspace": workspace,
            "canonical_root": self.root,
            "promotion_policy": "JAMES_SELFMADE_ALLOW_PROMOTION=1"
        })).await;

        Ok(serde_json::json!({
            "promoted": true,
            "workspace": workspace,
            "canonical_root": self.root
        }))
    }

    /// Roll back only the isolated SelfMade worktree. The canonical checkout is never touched.
    pub async fn rollback_workspace(&self) -> Result<serde_json::Value> {
        if !self.is_running().await {
            bail!("selfmade module is not running");
        }
        let workspace = self.ensure_workspace().await?;
        let output = Command::new("git")
            .current_dir(&workspace)
            .args(["reset", "--hard", "HEAD"])
            .output()
            .await?;
        if !output.status.success() {
            bail!("selfmade workspace rollback failed: {}", String::from_utf8_lossy(&output.stderr));
        }
        self.emit("selfmade.rollback.completed", serde_json::json!({
            "workspace": workspace,
            "stdout": String::from_utf8_lossy(&output.stdout)
        })).await;
        Ok(serde_json::json!({
            "rolled_back": true,
            "workspace": workspace
        }))
    }

    /// Cheap, deterministic verification first. Promotion to the canonical
    /// checkout is intentionally a separate policy-controlled operation.
    async fn verify_workspace(&self, workspace: &Path) -> Result<VerificationReport> {
        let mut checks = Vec::new();
        let mut stdout = String::new();
        let mut stderr = String::new();

        let git_check = Command::new("git")
            .current_dir(workspace)
            .args(["diff", "--check"])
            .output().await?;
        let git_ok = git_check.status.success();
        stdout.push_str(&String::from_utf8_lossy(&git_check.stdout));
        stderr.push_str(&String::from_utf8_lossy(&git_check.stderr));
        checks.push(VerificationCheck { name: "git-diff-check".into(), passed: git_ok });
        if !git_ok {
            return Ok(VerificationReport { passed: false, checks, stdout, stderr });
        }

        // JAMES is a multi-workspace repository. Verify the two Rust workspaces
        // independently instead of assuming a Cargo.toml at repository root.
        for (name, relative_dir, args) in [
            ("core-cargo-check", "runtime/core", vec!["check", "--workspace"]),
            ("core-cargo-test", "runtime/core", vec!["test", "--workspace"]),
            ("modules-cargo-check", "runtime/modules", vec!["check", "--workspace"]),
            ("modules-cargo-test", "runtime/modules", vec!["test", "--workspace"]),
        ] {
            let dir = workspace.join(relative_dir);
            let output = Command::new("cargo")
                .current_dir(&dir)
                .args(&args)
                .output().await?;
            let ok = output.status.success();
            stdout.push_str(&format!("\\n[{name}]\\n"));
            stdout.push_str(&String::from_utf8_lossy(&output.stdout));
            stderr.push_str(&String::from_utf8_lossy(&output.stderr));
            checks.push(VerificationCheck { name: name.into(), passed: ok });
            if !ok {
                return Ok(VerificationReport { passed: false, checks, stdout, stderr });
            }
        }
        Ok(VerificationReport { passed: true, checks, stdout, stderr })
    }

    async fn emit(&self, event_type: &str, payload: serde_json::Value) {
        let _ = self.event_bus.publish(Event::new(event_type, "james-selfmade").with_payload(payload)).await;
    }
}

pub fn manifest() -> ModuleManifest {
    ModuleManifest {
        id: "james.selfmade".into(),
        name: "James-SelfMade".into(),
        version: "0.1.0".into(),
        description: "Bounded autonomous software development and self-improvement runtime".into(),
        module_type: ModuleType::Custom,
        entry_point: "james_selfmade".into(),
        capabilities: vec![
            "selfmade.observe".into(),
            "selfmade.assess".into(),
            "selfmade.propose".into(),
            "selfmade.develop".into(),
            "selfmade.verify".into(),
            "selfmade.evaluate".into(),
            "selfmade.rollback".into(),
        ],
        dependencies: vec![],
        permissions: vec![],
        configuration_schema: Some(serde_json::json!({
            "type": "object",
            "properties": {
                "workspace": {"type": "string"},
                "autonomous_mode": {"type": "boolean", "default": false}
            }
        })),
        default_config: Some(serde_json::json!({
            "autonomous_mode": false
        })),
        author: Some("JAMES Project".into()),
        homepage: None,
        repository: None,
        license: "MIT".into(),
        tags: vec!["autonomy".into(), "development".into(), "self-improvement".into()],
        min_core_version: "0.1.0".into(),
        platforms: vec!["windows".into(), "linux".into(), "macos".into()],
    }
}

pub async fn register_capabilities(registry: &CapabilityRegistry) -> Result<()> {
    for (id, name, description, risk) in [
        ("selfmade.observe", "SelfMade Observe", "Inspect JAMES runtime and development state", RiskLevel::Low),
        ("selfmade.assess", "SelfMade Assess", "Assess a bounded self-improvement mission from current evidence", RiskLevel::Medium),
        ("selfmade.propose", "SelfMade Propose", "Create a bounded source change proposal", RiskLevel::Medium),
        ("selfmade.develop", "SelfMade Develop", "Generate, apply and verify a bounded source change in the isolated workspace", RiskLevel::High),
        ("selfmade.verify", "SelfMade Verify", "Run deterministic verification in isolated workspace", RiskLevel::Medium),
        ("selfmade.evaluate", "SelfMade Evaluate", "Evaluate a verified candidate before any promotion decision", RiskLevel::High),
        ("selfmade.rollback", "SelfMade Rollback", "Discard an unpromoted self-development workspace change", RiskLevel::High),
    ] {
        registry.register(CapabilityDefinition {
            id: id.into(),
            name: name.into(),
            category: CapabilityCategory::Custom("selfmade".into()),
            version: "1.0.0".into(),
            provider: "james.selfmade".into(),
            description: description.into(),
            risk_level: risk,
            required_permissions: vec![],
            dependencies: vec![],
            input_schema: None,
            output_schema: None,
            execution_target: ExecutionTarget::Local,
            tags: vec!["selfmade".into(), "development".into()],
            deprecated: false,
            experimental: true,
        }, "james.selfmade").await?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use james_events::EventBus;

    #[tokio::test]
    async fn evaluation_rejects_clean_candidate_without_changes() {
        let bus = Arc::new(EventBus::new(32));
        let registry = Arc::new(CapabilityRegistry::new());
        let module = SelfMadeModule::new(std::env::temp_dir().join(format!("james-selfmade-test-{}", Uuid::now_v7())), bus, registry);
        let report = module.evaluate_workspace().await;
        assert!(report.is_err() || !report.unwrap().passed);
    }

    #[tokio::test]
    async fn mission_starts_in_observe_state() {
        let bus = Arc::new(EventBus::new(32));
        let registry = Arc::new(CapabilityRegistry::new());
        let module = SelfMadeModule::new(".", bus, registry);
        let mission = module.new_mission("improve runtime");
        assert_eq!(mission.status, MissionStatus::Observing);
        assert!(!mission.id.is_empty());
    }

    #[tokio::test]
    async fn self_observation_contains_identity_and_capabilities() {
        let bus = Arc::new(EventBus::new(32));
        let registry = Arc::new(CapabilityRegistry::new());
        registry.register(CapabilityDefinition {
            id: "test.capability".into(),
            name: "Test".into(),
            category: CapabilityCategory::Custom("test".into()),
            version: "1.0.0".into(),
            provider: "test".into(),
            description: "test".into(),
            risk_level: RiskLevel::Low,
            required_permissions: vec![],
            dependencies: vec![],
            input_schema: None,
            output_schema: None,
            execution_target: ExecutionTarget::Local,
            tags: vec![],
            deprecated: false,
            experimental: false,
        }, "test").await.unwrap();
        let module = SelfMadeModule::new(std::env::temp_dir().join(format!("james-self-{}", Uuid::now_v7())), bus, registry);
        module.start().await.unwrap();
        let state = module.observe_self().await.unwrap();
        assert_eq!(state["identity"]["name"], "JAMES");
        assert_eq!(state["runtime"]["capability_count"], 1);
        let _ = tokio::fs::remove_dir_all(module.root.clone()).await;
    }

    #[tokio::test]
    async fn protected_authority_paths_are_rejected() {
        let bus = Arc::new(EventBus::new(32));
        let registry = Arc::new(CapabilityRegistry::new());
        let root = std::env::temp_dir().join(format!("james-self-protect-{}", Uuid::now_v7()));
        let module = SelfMadeModule::new(root.clone(), bus, registry);
        module.start().await.unwrap();
        let proposal = ChangeProposal {
            id: Uuid::now_v7().to_string(),
            mission_id: Uuid::now_v7().to_string(),
            cycle_id: None,
            objective: "test protection".into(),
            patch: "diff --git a/runtime/core/crates/james-capability-broker/src/lib.rs b/runtime/core/crates/james-capability-broker/src/lib.rs\n".into(),
            created_at: Utc::now(),
        };
        let result = module.apply_proposal(&proposal).await;
        assert!(result.is_err());
        let _ = tokio::fs::remove_dir_all(root).await;
    }

    #[tokio::test]
    async fn protected_patch_paths_reject_traversal_and_absolute_paths() {
        let bus = Arc::new(EventBus::new(32));
        let registry = Arc::new(CapabilityRegistry::new());
        let root = std::env::temp_dir().join(format!("james-self-paths-{}", Uuid::now_v7()));
        let module = SelfMadeModule::new(root.clone(), bus, registry);
        module.start().await.unwrap();

        for path in ["../outside.txt", "/absolute.txt", "runtime/core/crates/james-core/src/lib.rs"] {
            let proposal = ChangeProposal {
                id: Uuid::now_v7().to_string(),
                mission_id: Uuid::now_v7().to_string(),
                cycle_id: None,
                objective: "path safety".into(),
                patch: format!("diff --git a/{path} b/{path}\n"),
                created_at: Utc::now(),
            };
            assert!(module.apply_proposal(&proposal).await.is_err(), "path should be rejected: {path}");
        }

        let hidden_traversal = ChangeProposal {
            id: Uuid::now_v7().to_string(),
            mission_id: Uuid::now_v7().to_string(),
            cycle_id: None,
            objective: "header path safety".into(),
            patch: "diff --git a/safe.txt b/safe.txt\n--- a/safe.txt\n+++ b/../outside.txt\n".into(),
            created_at: Utc::now(),
        };
        assert!(module.apply_proposal(&hidden_traversal).await.is_err());

        let _ = tokio::fs::remove_dir_all(root).await;
    }

    #[test]
    fn patch_path_validation_is_independent_of_git() {
        assert!(validate_patch_paths("diff --git a/../outside.txt b/../outside.txt\n").is_err());
        assert!(validate_patch_paths("diff --git a//absolute.txt b//absolute.txt\n").is_err());
        assert!(validate_patch_paths("diff --git a/runtime/core/crates/james-core/src/lib.rs b/runtime/core/crates/james-core/src/lib.rs\n").is_err());
        assert!(validate_patch_paths("diff --git a/safe.txt b/safe.txt\n--- a/safe.txt\n+++ b/safe.txt\n").is_ok());
        assert!(validate_patch_paths("not a diff\n").is_err());
    }

    #[tokio::test]
    async fn manifest_is_selfmade() {
        assert_eq!(manifest().id, "james.selfmade");
    }
}
